[package]
name = "mywm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcb = "1.0.0-beta.4"
log = "0.4.14"
simple-logging = "2.0.2"